version: "3"
services:
  rproxy:
    image: nginx:mainline
    volumes:
      - ./certs:/root/certs
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - web

  web:
    build: .
    ports:
      - "8090:5000"
    depends_on:
      - store

  store:
    image: "redis:alpine"
